version: '3.8'

services:

  influxdb:
    image: influxdb:2.6-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - ./docker/influxdb/influxv2.env
    networks:
      - trader-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - trader-net

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      - trader-net
    environment:
      - ./docker/influxdb/influxv2.env

volumes:
  influxdb_data:

networks:
  trader-net:

